apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrade
  labels:
    app: ctrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctrade
  template:
    metadata:
      labels:
        app: ctrade
    spec:
      containers:
        - name: ctrade
          image: zeromaxinc/ctrade-group
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ctrade
spec:
  selector:
    app: ctrade
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 31211