name: Deployment workflow
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    

    - name: Build the Docker image
      run: docker build -t ctrade . && docker tag ctrade zeromaxinc/ctrade-group
    - name: Docker push
      run: docker push zeromaxinc/ctrade-group


    - name: Log in to Physical Server
      uses: appleboy/ssh-action@master
      with:
        host: 157.230.98.254
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/ctrade
          ls
          kubectl delete -f kubernetes.yaml
          kubectl apply -f kubernetes.yaml
    
 