name: Deployment workflow
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Server
      uses: appleboy/ssh-action@master
      with:
        host: 95.46.96.15
        username: docmeduz
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          git config --global user.email "abduaziz.botirov@mail.ru" && git config --global user.name "Abduaziz"
          cd /home/docmeduz
          rm -rf ctradegroup 
          git clone https://github.com/Umar23A/ctradegroup.git

