name: Deployment workflow
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Server
      uses: appleboy/ssh-action@master
      with:
        host: 95.46.96.15
        username: docmeduz
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/docmeduz/ctradegroup
          ls
          git pull

    # - name: Configuration Git
    #   run: git config --global user.email "test@gmail.com" && git config --global user.name "test"

