# Generated by Django 4.1.7 on 2023-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('text', models.TextField()),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('text', models.TextField()),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('text', models.TextField()),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('text', models.TextField()),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
    ]
